name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.0.0-dev.11
homepage: https://github.com/jhomlala/alice
repository: https://github.com/jhomlala/alice
topics:
  - http
  - inspector
  - dio
  - chopper
  - interceptor

environment:
  sdk: ^3.0.0
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: 9.9.1
  rxdart: ^0.27.7
  path_provider: ^2.0.9
  permission_handler: ^11.3.1
  package_info_plus: ^5.0.1
  open_filex: ^4.3.2
  sensors_plus: ^1.4.1
  share_plus: 7.2.2
  collection: ^1.18.0
  url_launcher: 6.3.0
  equatable: ^2.0.5
  get: 4.6.6
  draggable_float_widget: 0.1.0


dev_dependencies:
  flutter_lints: ^4.0.0